title: <p align="center"> Sushil Singh </p>
logo: /assets/img/Singh.PNG

description:
  <p align="center">
  <a href="pdf/Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sushil-singh-498bb223/">LinkedIn</a> |
  <a href="https://github.com/singhsushilmle">GitHub</a>
  
  <br>   
Worked across multiple domain Banking & financial, HealthCare & Insurance.
I have rich experince of 8 years in United State at client location.
Worked on various application development projects using Scrum/Agile methodologies.
  <br>
  </p>



theme: jekyll-theme-minimal
